# Generated by Django 4.1.2 on 2022-10-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_title_movie_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
    ]
